from book import Book
from recipe import Recipe

recipe_aaa = Recipe('aaa', 1, ['', 'aa', 'bb'], "bbbbbbbbbb.", "LUnch")

recipe_bbb = Recipe('bbb', 2, ['', 'cc', 'dd'], "dddddddddd.", "starTER")

print("==========recipe_aaa==========")
print(recipe_aaa.name)
print(recipe_aaa.cooking_lvl)
print(recipe_aaa.ingredients)
print(recipe_aaa.description)
print(recipe_aaa.recipe_type)
print()
print(recipe_aaa)
print("==========recipe_aaa==========")

print("==========recipe_bbb==========")
print(recipe_bbb.name)
print(recipe_bbb.cooking_lvl)
print(recipe_bbb.ingredients)
print(recipe_bbb.description)
print(recipe_bbb.recipe_type)
print()
print(recipe_bbb)
print("==========recipe_bbb==========")
print()

print("==========Book==========")
print("before adding===========")

book = Book("book_test")

print("  Book name:", book.name)
print("  Book last update date:", book.last_update)
print("  Book creation date:", book.creation_date)
print("  Book recipe list:", book.recipes_list)
print("before adding===========")
print()
print("after adding #1=========")
book.add_recipe(recipe_aaa)
print("  Book name:", book.name)
print("  Book last update date:", book.last_update)
print("  Book creation date:", book.creation_date)
print("  Book recipe list:", book.recipes_list)
print("after adding #1=========")
print()
print("after adding #2=========")
book.add_recipe(recipe_bbb)
print("  Book name:", book.name)
print("  Book last update date:", book.last_update)
print("  Book creation date:", book.creation_date)
print("  Book recipe list:", book.recipes_list)
print("after adding #2=========")
print()
print("get_recipes_by_types=========")
print("  Lunch:", book.get_recipes_by_types('lunch'))
print("  Starter:", book.get_recipes_by_types('starter'))
print("get_recipes_by_types=========")
print()
print("get_recipe_by_name=========")
print("  aaa:")
print(book.get_recipe_by_name('aaa'))
print("  bbb:")
print(book.get_recipe_by_name('bbb'))
print("get_recipe_by_name=========")
print()
print("  book with no name=====")
book_noname = Book()
print("  Book name:", book_noname.name)
print("  book with no name=====")
print()
print("==========Book==========")
